#!/usr/bin/env bash
set -e

supervisorctl stop lamassu-server
supervisorctl stop lamassu-admin-server
npm -g install lamassu/lamassu-server#v5.7.6 --unsafe-perm
lamassu-migrate
if [[ $(cat /etc/lamassu/lamassu.json) = *lamassuCaPath* ]]; then
        echo "No need to edit lamassu.json. Continuing..."
else
        sed -i '5i\ \ "lamassuCaPath":\ "/usr/lib/node_modules/lamassu-server/Lamassu_CA.pem",' /etc/lamassu/lamassu.json
        echo "lamassu.json updated."
fi
supervisorctl start lamassu-server
supervisorctl start lamassu-admin-server
echo "Upgrade complete."
