#!/usr/bin/env bash
set -e

supervisorctl stop lamassu-server
supervisorctl stop lamassu-admin-server
npm -g install lamassu/lamassu-server#v5 --unsafe-perm
lamassu-migrate
sed -i '5i\ \ "lamassuCaPath":\ "/usr/lib/node_modules/lamassu-server/Lamassu_CA.pem",' /etc/lamassu/lamassu.json
supervisorctl start lamassu-server
supervisorctl start lamassu-admin-server
